version: '3.8'

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 bot:app
    expose:
      - 5000
    env_file:
      - ./.env
