version: '3.7'
services:

  redis:
     image: "redis:alpine"
     volumes:
       - redis_data:/data

  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 bot:app
    expose:
      - 5000
    volumes:
      - app:/usr/src/app
    env_file:
      - ./.env

  beat:
    build: .
    command: celery --app=tasks.celery beat -l INFO
    depends_on:
      - redis
    volumes:
      - app:/usr/src/app
    env_file:
      - ./.env

  worker:
    build: .
    command: celery --app=tasks.celery worker -l INFO
    volumes:
      - .:/usr/src/app
    volumes:
      - app:/usr/src/app
    depends_on:
      - redis
    env_file:
      - ./.env

  dashboard:
    build: .
    command:  flower --app=tasks.celery --port=5555 --broker=redis://redis:6379/0
    ports:
      - 5556:5555
    depends_on:
      - web
      - redis
      - worker
    env_file:
      - ./.env

volumes:
    redis_data:
    app:
