version: '3.7'

services:
  web:
    build: .
    command: python bot.py
    volumes:
      - ./journal.db:/app/journal.db
      - ./conversation.txt:/app/conversation.txt
    env_file:
      - ./.env
