version: '3.8'

  redis:
    container_name: redis_dev_container
    image: redis
    ports:
      - "6379:6379"

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:5000 bot:app
    expose:
      - 5000
    env_file:
      - ./.env
    depends_on:
        - redis

services:
  nginx:
    build: ./nginx
    ports:
      - 80:80
    depends_on:
      - web
