version: '3.7'

services:
  web:
    build: .
    command: python bot.py
    volumes:
      - ./journal.sqlite:/app/journal.sqlite
      - ./conversation.txt:/app/conversation.txt
      - ./service-account.json:/app/service-account.json
    env_file:
      - ./.env
